### ISSUE TITLE
Burger nav dropdown at mobile view not working for all pages

### ISSUE THREAD

**Issue by STRAYKR** [CodeHubOrg/javascript101#54] opened 2017-03-30 10:03 UTC
Think the js/burgerNav.js script tag (in foot.html) is not being applied to the .md pages (about, careers, getting-started) so in mobile view the burger nav button does not work. I don't know how the navbar is applied... I can see that the .md file is rendered in routes.js and using utils/doc.js but how does it get the nav/footer etc?

**Comment by rinse0ut** [comment] 2017-03-30 10:42
The footer.pug view template needs to be updated with burgerNav.js

It is included by doc.pug whilst the layout.pug template includes the footer.html

**Comment by rinse0ut** [comment] 2017-03-30 10:50
Closing as duplicate of #32

**Closed as completed by rinse0ut** 2017-03-30 10:51 UTC
